### ISSUE TITLE
Cannot read property 'next' of null in v2.5.0

### ISSUE THREAD

**Issue by andrewaustin** [decaffeinate/decaffeinate#173]
When running decaffeinate for the first time I see:
```
$ decaffeinate .
master.coffee → master.js
master.coffee: Cannot read property 'next' of null
> 1 | #!/usr/bin/env ./node_modules/coffee-script/bin/coffee
    |
  2 |
  3 | "use strict"
```

Thought maybe it was an issue with ```#!``` but I get that error regardless of what the first line is. I tried with both the v2.5.0 tag and HEAD.

**Comment by bendoh** [comment]
Happens on my file too, completely different format. Seems to be just failing on the first line regardless.

**Comment by andrewaustin** [comment]
I tried again with v2.6.1, but got the same error.

```
$ node --version
v4.4.2
$ decaffeinate --version
decaffeinate v2.6.1
```

**Comment by eventualbuddha** [comment]
Can you guys provide some sample files?

**Comment by eventualbuddha** [comment]
Figured out how to reproduce it. Any file starting or ending with spaces will trigger it. I know how to fix it and will get to it soon.

**Comment by eventualbuddha** [comment]
Fixed in v2.7.1 ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=%20a%20%2B%20b%20)).

**Comment by andrewaustin** [comment]
I'm still seeing an issue, trying to create a reproducible case without sharing the entire file:

```
$ decaffeinate --version
decaffeinate v2.7.1
$ decaffeinate master.coffee
master.coffee → master.js
master.coffee: Cannot read property 'next' of null
> 1 | #!/usr/bin/env ./node_modules/coffee-script/bin/coffee
    |
  2 |
  3 | "use strict"
```

**Comment by andrewaustin** [comment]
Seems to blow up on:

```
appPath = "#{__dirname}/apps/#{APP.name}"
```

http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=appPath%20%3D%20%22%23%7B__dirname%7D%2Fapps%2F%23%7BAPP.name%7D%22%0A

**Comment by Eden-Sun** [comment]
@andrewaustin  #177
